### ISSUE TITLE
Training_data.csv?

### ISSUE THREAD

**Issue by CannedGeo** [seg/2016-ml-contest#10]
First, thanks for putting this exercise together. And also please excuse me stumbling through this as I learn pretty much from scratch. But, just wanted to clarify the csv file used in the paper is 'training_data', but the tutorial "facies_classification" notebook uses 'facies_vectors' then renamed to 'training_data', right? The absence of PE data for a couple wells in the tutorial that are not used in the paper (training_data.csv) is the main reason I ask. 

Thanks!
Bryan

**Comment by CannedGeo** [comment]
I'll go ahead and answer my own question on this one...my bad. We end up with same dataset after removing no PE wells, smh. When I first started this, I couldn't replicate the .43 F1 in the Facies_classification notebook. So when I started over new, only using code provided in the paper (and the training_data.csv), I got the .43.

**Comment by LukasMosser** [comment]
Thank you for this and welcome to GitHub!
If you're not yet on [SoftwareUnderground](http://swung.rocks) come and hang with the cool kids. ;-)

**Comment by kwinkunks** [comment]
I also just wanted to say a belated "Thanks!" to you @CannedGeo — I'm glad you made progress.
