### ISSUE TITLE
Where to find the closed issues

### ISSUE THREAD

**Issue by thanish** [seg/2016-ml-contest#21]
Hi @kwinkunks, first of all sorry of opening this issue which is more of a knowing Github than this contest. I'm logging back to this contest after few weeks. I'm lost where I have left it. I don't want to start over again the few of the analysis and the questions I raised before as all are closed now. But I am unable to see the closed issues. If I could view them and also few of the issues that were raised by other members and which closed now. I can get started easily.

**Comment by JesperDramsch** [comment]
hello thanish,

This should be what you are looking for

https://github.com/seg/2016-ml-contest/issues?q=is%3Aissue+is%3Aclosed

All the best
Jesper

Thanish notifications@github.com schrieb am Di., 22. Nov. 2016, 12:58:

**Comment by thanish** [comment]
ahhh Thank you so much @JesperDramsch. That's exactly what I was looking for. Now I can happily close this issue :)
