### ISSUE TITLE
Help with how to make submission

### ISSUE THREAD

**Issue by thanish** [seg/2016-ml-contest#27]
Hi guys, can some one tell me how to submit the results to this contest. I'm certainly new to github and everything seems out of my way. I'm not sure if my uploaded file was notified to the admin after I made the pull request. Infact I'm not sure if the pull request I did was correct. I'm not able to see my notebook like how it appears for the others. It looks like a html code for me. If you could post a short video right from forking or cloning to creating a separate folder for the team and uploading and submitting (pull request) the results it would be very helpful for beginners like me. I hope I'm not asking too much.

Thanks
Thanish

**Comment by thanish** [comment]
Hi is there going to be any help on this ?

**Comment by CannedGeo** [comment]
@thanish I struggled with this too and I still did it wrong. I included a couple screen shots that I hope will help. Once you are in the forked folder you want to submit ../thanish/2016-ml-contest/Mendacium click "Pull Request" as indicated in screenshot. Then next screen you should see the base fork (seg/2016-ml-contest) and then your folder for submittal as the head fork. Then you can click create pull request. Maybe there are other ways, but this should get you there. @kwinkunks is pro and may be able to help more. 

![image](https://cloud.githubusercontent.com/assets/22628826/20780902/22c2f792-b73c-11e6-9a24-10793fbb8322.png)
![image](https://cloud.githubusercontent.com/assets/22628826/20781000/d4b74f84-b73c-11e6-8828-3f13d9b6c89b.png)

**Comment by kwinkunks** [comment]
@thanish If you're still having trouble with this, let me know. @CannedGeo's description is spot-on... you can get to the same thing right from the top level of your repo, with this button:

![image](https://cloud.githubusercontent.com/assets/1692372/20887345/91817a86-bad0-11e6-9dba-97e1012c3783.png)

**Comment by thanish** [comment]
Thanks guys for the help. I will try to clean up my folder and try to run from the beginning as direct by @CannedGeo :)

**Comment by kwinkunks** [comment]
It seems like you have nailed this part of the workflow, so I'm closing this issue.

**Comment by thanish** [comment]
Yup I was able to achieve it. Just a quick question. How to upload the next submissions(code and predicted csv) ? Should I just upload them to the same folder and give the details about which is the code file and which is the csv file for this submission in the comments of the pull request ? or should I create a separate folder of each submissions ? Because I was thinking too many code files and csv files in one folder might cause confusions. Your thought please
