### ISSUE TITLE
Blind set inconsistent in article and Jupyter notebook

### ISSUE THREAD

**Issue by thanish** [seg/2016-ml-contest#3]
Can someone help me understand what is going to be the blind dataset ? 

In the index.ipynb  it has been said that the blind dataset is going to be same as used by Brendon

![image](https://cloud.githubusercontent.com/assets/4056145/19721855/b2d5ef18-9b91-11e6-84d2-d5276220ff13.png)

When I checked the jypter notebook I found that the blind data is the well NEWBY

![image](https://cloud.githubusercontent.com/assets/4056145/19721916/f690a0b8-9b91-11e6-9782-c6fa2d37cf73.png)

But in the magazine publish in Oct 2016 I could find that "SHANKLE" being used as the blind dataset.

![image](https://cloud.githubusercontent.com/assets/4056145/19721943/123726fc-9b92-11e6-919b-492e8ff218aa.png)

**Comment by kwinkunks** [comment]
Thank you for the question — and for pointing out the inconsistency. Very good question.

Take the printed article's lead: the **SHANKLE** well should be held blind.

I will update the notebooks and other documentation to reflect this.

Please also note that there may be a change to this rule, as we may have new blind data to test more fairly against. If there is a change, it will be before the end of November.

**Comment by kwinkunks** [comment]
@thanish Please feel free to create new issues for each question — one issue per question please, that will help us stay on top of everything. Sorry for the trouble, and thank you!

**Comment by thanish** [comment]
Okay @kwinkunks I have created separate issues as you have requested. But end of November sounds way to long :|

**Comment by kwinkunks** [comment]
@thanish I agree, I hope we resolve it before then. I guess I'm just trying to guarantee that it won't change after that.

**Comment by kwinkunks** [comment]
Fixed by b9f2b15fcf4b56bed54e5b69246f431df497426b
