### ISSUE TITLE
What is going to be the test set 

### ISSUE THREAD

**Issue by thanish** [seg/2016-ml-contest#5]
So which one exactly is going to be the test set ? 
is it the blind set(the Shankle well)  or anything else ?

**Comment by kwinkunks** [comment]
Notwithstanding the unresolved conversation in #2 — for now the validation test will be the SHANKLE well, as in the article (not the notebooks yet but I'm fixing them, see #8).

In other words, you are trying to beat the 0.43 F1 score that Brendon achieved against the SHANKLE well.

If there is a new truly blind set, which I hope we have soon, I will post this in #2 and also flag it in the contest documentation. We will strive to make everyone aware of it with several weeks left in the contest. It won't change after the end of November. If there's no new blind data by then, we will reconsider the F1 metric against the other option — probably some kind of k-fold CV metric.

Clsong this issue to keep the question of validation in #2.
