### ISSUE TITLE
Are all submission scores visible in the leader-board?

### ISSUE THREAD

**Issue by gccrowther** [seg/2016-ml-contest#54]
Hi @kwinkunks 

Enjoyable contest, thanks for the efforts you're putting in! Just wondering whether scores for all submissions are put into the leader board? Or only the top scores for each team? I haven't seen a score for my second submission and I wanted to ascertain how far off the mark it might be!!

Cheers,
George

**Comment by kwinkunks** [comment]
Hi George... ah, sorry about that. I left a comment on the PR >> https://github.com/seg/2016-ml-contest/pull/45

Indeed, only the top scores for each team are visible. I did have every submission on there at one point, but I was getting quite a few submissions so things were getting a bit out of hand. Maybe I should go back to that...

**Comment by gccrowther** [comment]
Ah, perfect, found it. Thanks very much, clearly needs some further consideration. I suspect your method of keeping track works just fine, I will know where to keep an eye out in future.

Cheers,
George
