### ISSUE TITLE
Is there a leaderboard

### ISSUE THREAD

**Issue by thanish** [seg/2016-ml-contest#6]
Hi is there going to be a leader board where we can see the score of our model and the other contributors ?

**Comment by kwinkunks** [comment]
Yes.

To be honest, I was waiting for (a) an entry, and (b) resolution of issue #2. But I suppose I could set it up sooner than that, with the footnote that it might change.

**Comment by LukasMosser** [comment]
What if we just added an issue where everyone can submit their score + link to notebook/repo?
