### ISSUE TITLE
Clarification on 3 files of same content 

### ISSUE THREAD

**Issue by thanish** [seg/2016-ml-contest#7]
I could see 3 files 
1. well_data_with_facies.csv 
2. validation_data_nofacies.csv
3. nofacies_data.csv
having the same data which possess info about 2 wells "STUART" , "CRAWFORD" with the same number of rows and the only difference being Facies column being present in "well_data_with_facies.csv". Please do clarify what is the use of these 3 datasets. I am guessing this is the test dataset on which the prediction should be done if the testset data is not blind data. Correct me if I am wrong

**Comment by kwinkunks** [comment]
Those wells were only a sort of footnote in the article, as an illustration of how we might apply the trained model to a problem where the facies are unknown — the typical purpose of a model. It was mainly to illustrate how to do this.

So, to put it another way: the wells STUART and CRAWFORD are of no use in the supervised learning problem and should be ignored.
