### ISSUE TITLE
Data description

### ISSUE THREAD

**Issue by thanish** [seg/2016-ml-contest#72]
Hi @kwinkunks I think I did see somewhere which explains about what each feature in the provided dataset means. But I am not sure though whether I really read the feature description. But in case if I'm missing something can you provide me the link for it or if it's not present now can you add it as data description in the repo ? Thanks

**Comment by Antoine-Cate** [comment]
The description of what the different physical properties measurements mean are in [this Notebook](https://github.com/seg/2016-ml-contest/blob/master/Facies_classification.ipynb). There is a lot of other information in the [paper](http://library.seg.org/doi/abs/10.1190/tle35100906.1) from Brendon Hall in TLE.
About the two geological variables:
NM_M indicates if the rock was deposited in the sea or on the continent (in an estuary for example). This basically divides facies in two groups with very low error.
The RELPOS variable, from what I have understood starts at 0 and ends at 1 for each marine-continental episode. Facies are deposited as sediments on top of each other in cycles (for example,  you start depositing in a continental environment, the water is rising, the sea comes in, and you continue depositing in a marine environment. Then the water level drops and you start a new cycle). Thus, RELPO gives insight on were you are in such cycle. If you want to know more about that, you should read about [sequence stratigraphy](https://en.wikipedia.org/wiki/Sequence_stratigraphy), which is a field of geology.

**Comment by thanish** [comment]
Thank you so much Antonie for the information :)
