### ISSUE TITLE
training dataset

### ISSUE THREAD

**Issue by wouterk1MSS** [seg/2016-ml-contest#90]
Uhm maybe a dumb question, but I see some people using "facies_vectors.csv" and others "training_data.csv". What is "the" training set or is it all up to us?

**Comment by kwinkunks** [comment]
It's not a dumb question, actually one well, KIMZEY A, is missing from `training_data.csv`, so you should use `facies_vectors.csv`. I think I will move that file to make this clearer.

**Comment by kwinkunks** [comment]
...maybe @brendonhall can comment if I'm missing something...

**Comment by adatum** [comment]
`training_data.csv` is a subset of `facies_vectors.csv`, and contains 3232 rows of complete cases. `facies_vectors.csv` contains those 3232 rows and an additional 917 more with missing values for the `PE` variable.  Of these, 466 are from well ALEXANDER D, 439 from well KIMZEY A, and 12 from well Recruit F9.

**Comment by brendonhall** [comment]
@adatum is correct.  `facies_vectors.csv` is the complete training set from the class website I originally obtained the data from.  For the article I removed the entries that didn't have the `PE` variable, and created a new data set `training_data.csv`.

**Comment by kwinkunks** [comment]
See also #10 - I should have spotted that before.
