### ISSUE TITLE
Facies Formations and NM_M

### ISSUE THREAD

**Issue by CannedGeo** [seg/2016-ml-contest#92]
I have been messing with things trying to see if a classifier would work well using the marine and non-marine formations and facies separately. This could be a terrible idea, but its also been fun for me learning code. Anyway! It looks like there may be some discrepancies in the data, where a NM facies (1,2,3) shows a M classifier (2) and vice versa that marine facies show a NM classifier. There are not a lot of them (total=~50), but they do exist. And are not present in all the wells but some wells have more than others (eg cross H). Has anyone else noticed this? Or maybe I'm just doing it wrong?? I made a notebook for this [here](SEG_contest_facies_NM_M/Facies_NM_M_relationship.ipynb). Also wonder how much it would actually affect predictions bc its a small number, and does the validation data contain the same discrepancies? Any thoughts? Thanks!! @kwinkunks 

Can also try this code to check.
`td_NM = training_data.loc[training_data['Facies'].isin([1,2,3])]`
`td_NM.loc[td_NM['NM_M'].isin([2])]`

**Comment by LukasMosser** [comment]
Hi @cannedgeo, I actually tried this as well and ran into that issue, I went on to just simply use the facies classes 123 and the rest to distinguish and for the prediction set I used the nm_m flag to separate the two datasets. Didn't improve my results though.

**Comment by kwinkunks** [comment]
Not sure I have a lot to add. This dataset is characteristically messy (OK, it's a lot tidier than *most* subsurface datasets). I think this is just part of the challenge I'm afraid, though I would say that personally I'd be inclined to trust the log data more than the interpreted data (marine/non-marine and RELPOS) --- that is, I'd hold it to a high 'standard of helpfulness'.

**Comment by CannedGeo** [comment]
Thanks @LukasMosser  and @kwinkunks for insight. I guess maybe its not enough to significantly influence  things, and probably just overthinking (or under??) on my part.  Thanks!
